# -*- coding: utf-8 -*-
"""onnx2tfpipe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkwRTJ_a9hOxA6rP0gOK-zyEw0846EVY
"""

!sudo apt-get -y update
!sudo apt-get -y install python3-pip
!sudo apt-get -y install python-is-python3
!wget https://github.com/PINTO0309/onnx2tf/releases/download/1.16.31/flatc.tar.gz \
  && tar -zxvf flatc.tar.gz \
  && sudo chmod +x flatc \
  && sudo mv flatc /usr/bin/
!pip install -U pip \
  && pip install tensorflow==2.19.0 \
  && pip install ai_edge_litert==1.2.0 \
  && pip install -U onnx==1.17.0 \
  && python -m pip install onnx_graphsurgeon \
        --index-url https://pypi.ngc.nvidia.com \
  && pip install -U onnxruntime==1.18.1 \
  && pip install -U onnxsim==0.4.33 \
  && pip install -U simple_onnx_processing_tools \
  && pip install -U onnx2tf \
  && pip install -U protobuf==3.19.6 \
  && pip install -U h5py==3.11.0 \
  && pip install -U psutil==5.9.5 \
  && pip install -U ml_dtypes==0.5.1 \
  && pip install -U tf-keras==2.19.0 \
  && pip install flatbuffers>=23.5.26

from google.colab import drive
drive.mount('/content/drive')

!pip install -U --no-deps \
tensorflowjs \
tensorflow_decision_forests \
ydf \
tensorflow_hub

!onnx2tf -i /content/drive/MyDrive/age_gender_new_new.onnx -ois input:1,3,224,224 -osd -dgc

!tensorflowjs_converter \
--input_format tf_saved_model \
--output_format tfjs_graph_model \
saved_model \
tfjs_model!

from google.colab import drive
drive.mount('/content/drive')          # run once per session – follow the auth link

# pick a folder name inside Drive (creates it if missing)
DEST = "/content/drive/MyDrive/new_model"

!mkdir -p "$DEST"
!cp -r /content/saved_model  "$DEST/"
!cp -r /content/tfjs_model!   "$DEST/"

print("✅ copied to", DEST)

import tensorflow as tf
import numpy as np
from PIL import Image

# 1. Load the SavedModel you pointed tensorflowjs_converter at
model = tf.saved_model.load("/content/saved_model")
infer = model.signatures["serving_default"]

# 2. Prepare your image
def preprocess(path):
    img = Image.open(path).convert("RGB").resize((224,224))
    arr = np.array(img).astype(np.float32) / 255.0
    # If you used ImageNet normalization:
    mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
    std  = np.array([0.229, 0.224, 0.225], dtype=np.float32)
    arr = (arr - mean) / std
    return tf.expand_dims(arr, axis=0)  # shape: (1,224,224,3)

# path to your test image
img_path = "/content/drive/MyDrive/308909_v9_bb.jpg"
input_tensor = preprocess(img_path)

# 3. Run inference
outputs = infer(input_tensor)

# 4. Print raw outputs
# Depending on your model signature, keys might be something like 'age_head' and 'gender_head'
for name, tensor in outputs.items():
    print(f"{name}: {tensor.numpy().squeeze()}")

# e.g. you might see:
#   age_logits: 32.847
#   gender_head/MatMul: 0.7235   (this is before sigmoid if you didn’t bake it in)